/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
});
export const DemoRequestStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const DemoRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : DemoRequestStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Int,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const SubscriberStatus = IDL.Variant({
  'active' : IDL.Null,
  'unsubscribed' : IDL.Null,
});
export const Subscriber = IDL.Record({
  'status' : SubscriberStatus,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDemoRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'subscribe' : IDL.Func([IDL.Text], [], []),
  'unsubscribe' : IDL.Func([IDL.Text], [], []),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateDemoRequestStatus' : IDL.Func([IDL.Nat, DemoRequestStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
  });
  const DemoRequestStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const DemoRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : DemoRequestStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Int,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const SubscriberStatus = IDL.Variant({
    'active' : IDL.Null,
    'unsubscribed' : IDL.Null,
  });
  const Subscriber = IDL.Record({
    'status' : SubscriberStatus,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDemoRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'subscribe' : IDL.Func([IDL.Text], [], []),
    'unsubscribe' : IDL.Func([IDL.Text], [], []),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateDemoRequestStatus' : IDL.Func([IDL.Nat, DemoRequestStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };