/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'tags' : Array<string>,
  'author' : string,
  'summary' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface DemoRequest {
  'id' : bigint,
  'status' : DemoRequestStatus,
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'preferredDate' : bigint,
  'timestamp' : bigint,
  'phone' : string,
}
export type DemoRequestStatus = { 'scheduled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface Lead {
  'id' : bigint,
  'source' : string,
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Subscriber {
  'status' : SubscriberStatus,
  'email' : string,
  'timestamp' : bigint,
}
export type SubscriberStatus = { 'active' : null } |
  { 'unsubscribed' : null };
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'role' : string,
  'quote' : string,
  'company' : string,
  'avatarUrl' : string,
  'rating' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLead' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addTestimonial' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, string, string, string, Array<string>],
    bigint
  >,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDemoRequests' : ActorMethod<[], Array<DemoRequest>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getSubscribers' : ActorMethod<[], Array<Subscriber>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDemoRequest' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
  'subscribe' : ActorMethod<[string], undefined>,
  'unsubscribe' : ActorMethod<[string], undefined>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, string, string, string, Array<string>],
    undefined
  >,
  'updateDemoRequestStatus' : ActorMethod<
    [bigint, DemoRequestStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];