import { Badge } from "@/components/ui/badge";
import { Link } from "@tanstack/react-router";
import { AlertTriangle } from "lucide-react";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-xl font-bold font-heading text-[#0A1628] mb-3 border-b border-gray-200 pb-2">{title}</h2>
      <div className="text-gray-600 leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function DisclaimerPage() {
  return (
    <div className="pt-16">
      <section className="bg-gradient-to-br from-[#0A1628] to-[#1F3A93] py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <Badge className="bg-white/10 text-white border-white/20 mb-4">Legal</Badge>
          <h1 className="text-3xl sm:text-4xl font-bold font-heading text-white mb-3">Disclaimer</h1>
          <p className="text-gray-300">Last updated: January 1, 2026</p>
        </div>
      </section>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-orange-50 border border-orange-200 rounded-xl p-5 mb-8 flex gap-3">
          <AlertTriangle className="w-5 h-5 text-orange-600 shrink-0 mt-0.5" />
          <p className="text-orange-800 text-sm leading-relaxed">
            <strong>Important:</strong> The AI-powered predictions, forecasts, scores, and recommendations provided by NexVstar AI Technology Pvt. Ltd. are intended to assist decision-making and are advisory in nature only. They do not constitute financial, legal, or professional advice. All business decisions remain the sole responsibility of the client organization.
          </p>
        </div>

        <Section title="1. General Disclaimer">
          <p>
            The information, data, analysis, predictions, and recommendations ("AI Outputs") provided through the NexVstar AI platform are generated by machine learning models and are provided for informational and decision-support purposes only.
          </p>
          <p>
            NexVstar AI Technology Pvt. Ltd. makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the AI Outputs.
          </p>
        </Section>

        <Section title="2. AI Predictions Are Advisory">
          <p>
            All AI-generated predictions including but not limited to:
          </p>
          <ul className="list-disc ml-6 space-y-1">
            <li>Lead conversion probability scores</li>
            <li>Revenue forecasts and projections</li>
            <li>Sales cycle duration estimates</li>
            <li>Market trend predictions</li>
            <li>Customer behavior forecasts</li>
            <li>ROI calculations and estimates</li>
          </ul>
          <p className="mt-2">
            ...are based on historical data patterns, statistical models, and algorithms that may not account for all market variables, economic conditions, or business-specific factors. <strong>Actual results may differ materially from predictions.</strong>
          </p>
        </Section>

        <Section title="3. No Financial Advice">
          <p>
            Nothing on the NexVstar platform constitutes financial advice, investment recommendations, or securities advice. Revenue projections and financial forecasts are estimates based on input data and should not be used as the sole basis for financial planning, fundraising, or investment decisions without independent professional review.
          </p>
        </Section>

        <Section title="4. Client Responsibility">
          <p>
            Clients are solely responsible for:
          </p>
          <ul className="list-disc ml-6 space-y-1">
            <li>All business decisions made based on AI Outputs</li>
            <li>Verifying the accuracy of data entered into the platform</li>
            <li>Ensuring their use of the platform complies with applicable laws</li>
            <li>Reviewing AI recommendations before implementation</li>
            <li>Maintaining independent professional advisors as appropriate</li>
          </ul>
        </Section>

        <Section title="5. Data Accuracy">
          <p>
            The accuracy of AI Outputs is directly dependent on the quality and completeness of data provided by the client. NexVstar AI Technology Pvt. Ltd. does not verify the accuracy of client-submitted data and shall not be liable for errors arising from inaccurate, incomplete, or outdated input data.
          </p>
        </Section>

        <Section title="6. Third-Party Integrations">
          <p>
            The NexVstar platform may integrate with third-party services (CRM systems, email platforms, LinkedIn, etc.). We are not responsible for the accuracy, availability, or policies of these third-party services. Data obtained from third-party integrations may be subject to additional terms and limitations.
          </p>
        </Section>

        <Section title="7. Past Performance">
          <p>
            Case studies, testimonials, and reported ROI figures presented on this platform represent the experiences of specific clients under specific conditions. They are not indicative of results that any particular client can or should expect. Past performance of the platform or client results does not guarantee future performance.
          </p>
        </Section>

        <Section title="8. Technology Limitations">
          <p>
            Artificial intelligence and machine learning technologies are subject to inherent limitations, including:
          </p>
          <ul className="list-disc ml-6 space-y-1">
            <li>Potential for algorithmic bias in scoring models</li>
            <li>Dependency on training data quality and recency</li>
            <li>Inability to fully predict human behavior</li>
            <li>Sensitivity to unusual market conditions or black swan events</li>
          </ul>
          <p className="mt-2">
            NexVstar continuously improves its models but cannot guarantee perfect accuracy at all times.
          </p>
        </Section>

        <Section title="9. Indemnification">
          <p>
            By using the NexVstar platform, clients agree to indemnify and hold harmless NexVstar AI Technology Pvt. Ltd., its directors, employees, and affiliates from any claims, damages, or liabilities arising from reliance on AI Outputs or decisions made based on platform recommendations.
          </p>
        </Section>

        <Section title="10. Governing Jurisdiction">
          <p>
            This disclaimer is governed by the laws of India. Any disputes shall be resolved under the jurisdiction of courts in Mumbai, Maharashtra, India, in accordance with the Indian IT Act 2000 and applicable regulations.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>For questions regarding this disclaimer, contact us at legal@nexvstar.ai</p>
          <address className="not-italic mt-2 text-sm bg-gray-50 rounded-lg p-4">
            <strong>NexVstar AI Technology Pvt. Ltd.</strong><br />
            Mumbai, Maharashtra, India<br />
            Email: legal@nexvstar.ai<br />
            Phone: +91 98765 43210
          </address>
        </Section>

        <div className="border-t border-gray-200 pt-6 mt-6">
          <div className="flex flex-wrap gap-4 text-sm text-gray-500">
            <Link to="/legal/terms" className="text-[#6C63FF] hover:underline">Terms & Conditions</Link>
            <Link to="/legal/privacy" className="text-[#6C63FF] hover:underline">Privacy Policy</Link>
            <Link to="/legal/cookies" className="text-[#6C63FF] hover:underline">Cookie Policy</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
